name: Docker Build and Push

on:
  push:
    branches:
      - practical

jobs:
  build_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.connie888 }}
          password: ${{ secrets.Gandr0108* }}

      - name: Build & Push Production Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: connie888/prediction_app:prod

  build_dev:
    runs-on: ubuntu-latest
    needs: build_prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.connie888 }}
          password: ${{ secrets.Gandr0108* }}

      - name: Build & Push Development Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: connie888/prediction_app:dev

  test:
    runs-on: ubuntu-latest
    needs: [build_prod, build_dev]
    steps:
    - name: Run Tests
      run: |
        echo "Testing build success"
        docker pull connie888/prediction_app:prod
        docker pull connie888/prediction_app:dev
        echo "Both images were pulled successfully"
